#!/usr/bin/env groovy

pipeline {
    
    tools { 
        maven 'maven-3.5.0'
	    jdk 'java8' 
    }
    
    agent { label 'DL-Team' }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    echo "JAVA_HOME = ${JAVA_HOME}"
                '''
            }
        }
        
        stage('Checkout') {
            agent { label 'DL-Team' }
            steps {
                checkout scm
            }
        }
        stage ('Build') {
            agent { label 'DL-Team' }
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
        
        stage('Deploy') {
            agent { label 'DL-Team' }
            steps {
                echo "deploying"
                
                withCredentials([
                    string(credentialsId: 'ee-host', variable: 'HOST'),
                    string(credentialsId: 'ee-user', variable: 'USER')
                ]) {
                    sh '''
                        scp target/*.jar ${USER}@${HOST}:/home/${USER}/dei/artifacts
                        ssh ${USER}@${HOST}  "sudo systemctl restart dei"
                    '''
                }
            }
        }

    }
}
